# 04 - Model Training and Prediction

**Objective:** Train classification models on Wine data and evaluate performance.

**Steps:**
1. Load engineered data and split into train/test
2. Scale features (for distance-based models)
3. Train multiple classification models
4. Evaluate and compare models
5. Log experiments with MLflow
6. Save models for later use

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

import joblib

print("Libraries imported successfully")

## Data Loading

In [ ]:
# TODO: Load the engineered data from data/processed/engineered_data.csv
# If it doesn't exist, load clean_data.csv instead.
# Wine has 13 numerical features (chemical measurements) and a 3-class target.
# Target column is 'class' (0=cultivar_1, 1=cultivar_2, 2=cultivar_3).

PROCESSED_DIR = Path("../data/processed")

# TODO: Try to load engineered data, fallback to clean data
# Hint: Check if engineered_data.csv exists using Path.exists()

# TODO: Separate features and target
# Drop 'class' to get X, keep it as y.

# df = pd.read_csv(PROCESSED_DIR / "engineered_data.csv")
# X = df.drop(columns=["class"])
# y = df["class"]
# print(f"Features: {X.shape}, Target: {y.shape}")
# print(y.value_counts())

In [ ]:
# TODO: Split data into train and test sets
# Use train_test_split() to generate X_train, X_test, y_train, y_test.
# Use stratify=y to preserve the class balance in both splits.
# Set test_size=0.2 and random_state=42 for reproducibility.
# Wine has 178 samples (59/71/48 per class), so test will have ~36 samples.
#
# print(f"Train: {X_train.shape}, Test: {X_test.shape}")
# print(f"Train class balance:\n{y_train.value_counts(normalize=True)}")

## Feature Scaling

In [ ]:
# TODO: Scale features for Logistic Regression, SVC
# Define a StandardScaler and fit on the training data only.
# Use fit_transform() on X_train and transform() on X_test to prevent data leakage.
#
# TODO: Verify scaling
# print(f"Mean after scaling: {X_train_scaled.mean(axis=0)[:5]}")
# print(f"Std after scaling: {X_train_scaled.std(axis=0)[:5]}")
# Check with np.allclose() that the mean is near 0 and std near 1.

## Model Training

Scikit-learn provides a consistent API for training various models.

Every predictor in scikit-learn has a `fit()` method for training and a `predict()` method for making predictions.

Each model has its own strengths and weaknesses, so we will train multiple models to compare their performance.

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [ ]:
# TODO: Train Logistic Regression model (multiclass)
# Define a LogisticRegression classifier with multi_class='multinomial'.
# Set max_iter=1000 to ensure convergence. Fit on the scaled training data.
# Check the coefficients (shape should be 3 classes x 13 features).
# 

In [ ]:
# TODO: Train Random Forest model
# Define a RandomForestClassifier.
# Specify the number of trees with n_estimators (e.g., n_estimators=100).
# Fit on the training data and check feature importances.

In [ ]:
# TODO: Train XGBoost model (multiclass)
# Define an XGBClassifier.
# Set objective='multi:softprob' and eval_metric='mlogloss' for multiclass.
# Set random_state=42.
# XGBoost is a powerful gradient boosting algorithm that often performs well on structured data.
# You can specify n_estimators, learning_rate, and max_depth.
# Fit on the training data and check feature importances.

In [ ]:
# TODO: Train SVC model (uses scaled features)
# Define an SVC with kernel='rbf'.
# SVC is a classification algorithm that can capture non-linear relationships.
# Fit on the scaled training data and check the number of support vectors.

In [ ]:
# TODO: Train Decision Tree model
# Define a DecisionTreeClassifier.
# Specify max_depth to control overfitting (e.g., max_depth=5).
# Fit on the training data and check feature importances.

### The Confusion Matrix

The confusion matrix is a table that summarizes the performance of a classification model. For multiclass problems (3+ classes), it becomes a K x K grid where rows are actual classes and columns are predicted classes.

|               | Predicted A | Predicted B | Predicted C |
|---------------|-------------|-------------|-------------|
| Actual A      |    TP_A     |    E_AB     |    E_AC     |
| Actual B      |    E_BA     |    TP_B     |    E_BC     |
| Actual C      |    E_CA     |    E_CB     |    TP_C     |

Each diagonal cell shows correct predictions (true positives for that class), while off-diagonals show misclassifications. Instead of a single 2x2 table, we get per-class TP/FP/FN counts.

Wine is a 3-class problem (cultivar_1=0, cultivar_2=1, cultivar_3=2), so our confusion matrix will be 3x3.

```python
from sklearn.metrics import confusion_matrix

y_true = [0, 1, 2, 0, 1, 2]  # Actual labels
y_pred = [0, 1, 1, 0, 2, 2]  # Predicted labels

cm = confusion_matrix(y_true, y_pred)
print(cm)
# [[2 0 0]
#  [0 1 1]
#  [0 1 1]]
```

In [ ]:
# TODO: Plot the confusion matrix of a selected model (e.g., Random Forest)
# For multiclass, use a heatmap with class names (cultivar_1, cultivar_2, cultivar_3) as labels.
# import seaborn as sns
# import matplotlib.pyplot as plt

## Prediction & Evaluation

Predictions are made using the `predict()` method of the trained model.

Classification models are evaluated using metrics like:
- **Accuracy**: Proportion of correct predictions
- **Precision**: Proportion of positive identifications that were correct (multiclass uses averaging)
- **Recall**: Proportion of actual positives that were identified correctly
- **F1-score**: Harmonic mean of precision and recall

For multiclass problems (3+ classes), we use `average='weighted'` to combine per-class scores weighted by class support.

In [ ]:
# TODO: Make predictions with each model and evaluate
# model_dictionary = {
#     "LogisticRegression": lr_model,
#     "RandomForest": rf_model,
#     "XGBoost": xgb_model,
#     "SVC": svc_model,
#     "DecisionTree": dt_model
# }
#
# For each model:
# - Make predictions on the test set (use scaled features for LR and SVC).
# - Calculate evaluation metrics with average='weighted': accuracy, precision, recall, F1.
# - Print the results in a formatted way.
# - Store the results in a dictionary for later comparison:
#   results = {
#       "LogisticRegression": {"Accuracy": acc, "Precision": prec, "Recall": rec, "F1": f1},
#       ...
#   }

In [ ]:
# TODO: Compare the performance of the models
# Create a DataFrame from the results dictionary:
# results_df = pd.DataFrame(results).T
# Use seaborn or matplotlib to create a bar plot comparing metrics across models.
#
# import seaborn as sns
# import matplotlib.pyplot as plt

In [ ]:
# TODO: Plot feature importance for tree-based models
# Importances are in rf_model.feature_importances_ and xgb_model.feature_importances_.
# They correspond to the columns in X_train.
# Use sns.barplot(x="importance", y="feature", data=top_features)
# to plot the top features for Random Forest and XGBoost.

## Model Interpretability with SHAP

SHAP (SHapley Additive exPlanations) is a game-theoretic approach to explain the output of machine learning models. It provides consistent and locally accurate feature importance values by computing Shapley values from cooperative game theory.

Unlike traditional feature importance (which tells you which features matter globally), SHAP explains individual predictions — showing how each feature contributed to pushing a prediction away from the average.

### SHAP vs Traditional Feature Importance

While the bar charts above show global feature importance (average reduction in impurity across all trees), SHAP values provide:

- **Local explanations**: How each feature affects individual predictions
- **Consistency**: If a model changes so a feature matters more, its SHAP value never decreases
- **Directionality**: SHAP shows whether a feature pushes predictions up or down from the average

In [ ]:
# TODO: Compute SHAP values for the Random Forest model
# Use shap.TreeExplainer(rf_model) to create an explainer.
# For multiclass, shap_values is a list of arrays (one per class).
#
# import shap
# explainer = shap.TreeExplainer(rf_model)
# shap_values = explainer.shap_values(X_test)
# # Use the first class (class 0) for visualization
# sv = shap_values[0] if isinstance(shap_values, list) else shap_values
# print(f"SHAP values shape: {sv.shape}")

In [ ]:
# TODO: Create a SHAP summary plot
# Use shap.summary_plot() with the SHAP values and feature names.
#
# shap.summary_plot(sv, X_test, feature_names=feature_names)

In [ ]:
# TODO: Create a SHAP dependence plot
# Choose a feature and use shap.dependence_plot() to show how it affects predictions.
#
# feature = 'alcohol'
# shap.dependence_plot(feature, sv, X_test, feature_names=feature_names)

In [ ]:
# TODO: Create a SHAP waterfall plot for one predicted class
# Pick a sample from X_test and use shap.plots.waterfall() to visualize feature contributions.
# For multiclass, use [:,:,class_idx] for the desired class.
#
# y_pred = rf_model.predict(X_test)
# sample_idx = 0
# pred_class = y_pred[sample_idx]
# shap.plots.waterfall(explainer(X_test)[:,:,pred_class][sample_idx])

In [ ]:
# TODO: Create a SHAP waterfall plot for a different class
# Find a sample predicted as a different class and visualize that prediction.
#
# idx = np.where(y_pred == 1)[0][0]
# shap.plots.waterfall(explainer(X_test)[:,:,1][idx])

## MLflow Tracking

MLflow is an open-source platform for managing the machine learning lifecycle, including experimentation, reproducibility, and deployment. We will use MLflow to log our model training experiments, including parameters, metrics, and artifacts.

### Logging Experiments

- Setting up MLflow tracking

**Runs**: Each time you train a model, you can log it as a run in MLflow. You can log parameters (e.g., model hyperparameters), metrics (e.g., accuracy, F1), and artifacts (e.g., trained model files).

**Experiments**: Experiments are a collection of runs. You can organize your runs into experiments to keep track of different model training sessions.

```python
import mlflow
mlflow.set_experiment("Wine Classification")
with mlflow.start_run(run_name="Random Forest"):
    rf_model.fit(X_train, y_train)
    y_pred = rf_model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')
    mlflow.log_param("model_type", "RandomForest")
    mlflow.log_metric("accuracy", acc)
    mlflow.log_metric("f1", f1)
    mlflow.sklearn.log_model(rf_model, "random_forest_model")
```

In [ ]:
# TODO: Use a loop to train, evaluate, and log all models with MLflow
# This will help you avoid code repetition and make it easier to compare results.
# Wrap each model's training and evaluation in an mlflow.start_run() context.

### Model Saving & Loading

After training, we can save our models using `joblib` or `pickle` for later use. This allows us to load the trained model without retraining it, which is especially useful for deployment.

joblib is often preferred for saving scikit-learn models because it is more efficient at handling large numpy arrays, which are common in machine learning models.

pickle can also be used, but it may not be as efficient for large models.

In [ ]:
# TODO: Save the best performing model using joblib for later use
# For bonus points, select the best model based on a specific metric (e.g., highest F1) and save it with a descriptive name.

MODELS_DIR = Path("../models")
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# joblib.dump()

In [ ]:
# TODO: Load models and verify predictions match
# Use joblib.load() to load the model and make predictions on X_test.
# Compare to original predictions using assert.

## Data Saving

Large datasets can be saved in efficient formats like Parquet or HDF5, which support fast read/write operations and compression. This is especially useful when working with large datasets that may not fit into memory.

**Parquet** is a columnar storage file format that is optimized for performance and storage efficiency.

Saving and loading data in parquet format is made easy with pandas using the `.to_parquet()` and `.read_parquet()` methods.

In [ ]:
# TODO: Save evaluation results for later analysis
# Save the results DataFrame to a CSV or Parquet file in the processed directory.

### Exercises

1. **Add new model**: Try training a KNeighborsClassifier and compare performance.
2. **Feature importance**: Use RandomForestClassifier's feature_importances_ to identify key features.
3. **Confusion matrix**: Plot confusion matrices for each model to visualize misclassifications.
4. **Cross-validation**: Use cross_val_score to get more robust performance estimates.
5. **What's missing?**: Can you think of something that will be important to apply this model in the real world?